#Heatpump Automations
#some automations: load warmwater every day at 14:00 for 30minutes
- alias: "WP_Warmwasser_Load"
  trigger:
    - platform: time
      at: "14:00:00"
  action:
    - service: modbus.write_register
      data:
        hub: wpump
        address: 42102
        slave: 1
        value: 30
  mode: single

# - name: "SystembetriebsartChange"
#   unique_id: wpump_mode
#   state: "{{ states('sensor.wp_systembetriebsart_text') }}"
#   options: "{{ ['Automatik', 'Heizen', 'Kühlen', 'Sommer', 'Standby', '2. WEZ']}}"
#   select_option:
#     service: modbus.write_register
#     data:
#       hub: wpump
#       slave: 1
#       address: 40001
#       value: >
#         {% if option == "Automatik" %} 0
#         {% elif option == "Heizen" %} 1
#         {% elif option == "Kühlen" %} 2
#         {% elif option == "Sommer" %} 3
#         {% elif option == "Standby" %} 4
#         {% elif option == "2. WEZ" %} 5
#         {% endif %}