mqtt:
  sensor:
    #### ELTAKO related ####
    - name: WW_eltako_current_meter
      state_topic: "heatpump/power_consumption/current_meter"
      unit_of_measurement: "Wh"
    - name: WW_eltako_power
      state_topic: "heatpump/power_consumption/power"
      unit_of_measurement: "W"
      device_class: power
    #### ZISTERN related ####
    #{"Time":"2024-02-14T22:03:04","ANALOG":{"Range": 1755}}
    - name: ZZ_range # zistern range
      state_topic: "tele/zisterne/SENSOR"
      value_template: "{{ value_json.ANALOG.Range }}"
      unit_of_measurement: "range"
    #### DHT22 related ####
    - name: DHT_temperature1
      state_topic: "hygrometer/cellar_1/temperature"
      unit_of_measurement: °C
      state_class: measurement      
      device_class: temperature
    - name: DHT_temperature2
      state_topic: "hygrometer/cellar_2/temperature"
      unit_of_measurement: °C
      state_class: measurement      
      device_class: temperature
    - name: DHT_humidity1
      state_topic: "hygrometer/cellar_1/humidity"
      unit_of_measurement: '%'
    - name: DHT_humidity2
      state_topic: "hygrometer/cellar_2/humidity"
      unit_of_measurement: '%'